spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: create # ddl-auto

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
