spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
    hibernate:
      ddl-auto: create # ddl-auto
  datasource:
    hikari:
      maximum-pool-size: 20
  session:
    store-type: redis

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

server:
  tomcat:
    threads:
      max: 50
    accept-count: 10
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

jvm:
  args:
    scheduler: true
