name: checkmate-backend-CI

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - backend/**
    types: [ opened, synchronize ]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: Change gradlew permission
        run: sudo chmod 755 gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Add comment when test fail
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: Add test results to PR
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: Add Coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          title: 📝 Test Coverage Report
          paths: ${{ github.workspace }}/backend/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
