name: checkmate-frontend-CI

env:
  API_SERVER_HOST: https://dev.checkmate.today
  CLIENT_ID: 384532281638-939rf8dpjt0hdd9tggkdpjfk7neu6sht.apps.googleusercontent.com

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - frontend/**
    types: [opened, synchronize]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Prerequisites
        run: sudo apt-get update && sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb && echo 'API_SERVER_HOST=${API_SERVER_HOST}' > .env && echo 'CLIENT_ID=${CLIENT_ID}' >> .env
      - name: E2E test
        run: npm ci && npm run test:ci
