name: checkmate-frontend-CI

env:
  API_SERVER_HOST: ${{ secrets.DEV_API_SERVER_HOST }}
  CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - frontend/**
    types: [opened, synchronize]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          echo 'API_SERVER_HOST=${API_SERVER_HOST}' > .env
          echo 'CLIENT_ID=${CLIENT_ID}' >> .env

      - name: E2E test
        run: npm ci && npm run test:ci
