name: checkmate-sonarqube

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: recursive

  analysis:
    runs-on: ubuntu-latest
    env:
      SONARQUBE_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_NAME }}
      SONARQUBE_URL: ${{ secrets.SONAR_HOST_URL }}
      SONARQUBE_TOKEN : ${{ secrets.SONAR_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
#      TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
#      TOKEN_EXPIRE_LENGTH: ${{ secrets.TOKEN_EXPIRE_LENGTH }}
#      GOOGLE_CLENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#      GOOGLE_CLENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
#      GOOGLE_GRANT_TYPE: ${{ secrets.GOOGLE_GRANT_TYPE }}
#      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
      
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: recursive
        
      - name: gradlew permission change
        run: sudo chmod 755 gradlew

      - name: Sonaqube Analysis
        run: ./gradlew test sonarqube
          -Dsonar.host.url=${{ env.SONARQUBE_URL }}
          -Dsonar.projectKey=${{ env.SONARQUBE_PROJECT_KEY }}
          -Dsonar.projectName=${{ env.SONARQUBE_PROJECT_KEY }}-${{ env.PR_NUMBER }}
          -Dsonar.login=${{ env.SONARQUBE_TOKEN }}
#          -Dsecurity.jwt.token.secret-key=${{ env.TOKEN_KEY }}
#          -Dsecurity.jwt.token.expire-length=${{ env.EXPIRE_LENGTH }}
#          -Doauth2.google.client-id=${{ env.GOOGLE_CIENT_ID }}
#          -Doauth2.google.client-secret=${{ env.GOOGLE_CLIENT_SECRET }}
#          -Doauth2.google.grant-type=${{ env.GOOGLE_GRANT_TYPE }}
#          -Doauth2.google.redirect-uri=${{ env.GOOGLE_REDIRECT_URI }}
        
      - name: Comment Sonarqube URL
        uses: actions/github-script@v4
        with:
          script: |
            const { SONARQUBE_PROJECT_KEY, SONARQUBE_URL, PR_NUMBER } = process.env
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📊 ${ SONARQUBE_PROJECT_KEY }-${ PR_NUMBER } 분석 결과 확인하기 [링크](${SONARQUBE_URL})`
            })
